export const PORTONE_STORE_ID = process.env.NEXT_PUBLIC_PORTONE_STORE_ID ?? ""
export const PORTONE_CHANNEL_KEY = process.env.NEXT_PUBLIC_PORTONE_CHANNEL_KEY ?? ""
export const PAYMENT_REDIRECT_URL = process.env.NEXT_PUBLIC_PAYMENT_REDIRECT_URL ?? ""
