import { env } from "@/shared/config/env"

export const PORTONE_STORE_ID = env.NEXT_PUBLIC_PORTONE_STORE_ID
export const PORTONE_CHANNEL_KEY = env.NEXT_PUBLIC_PORTONE_CHANNEL_KEY
export const PAYMENT_REDIRECT_URL = env.NEXT_PUBLIC_PAYMENT_REDIRECT_URL
